# Copyright Vespa.ai. All rights reserved.
shared:
  image: docker.io/vespaengine/vespa-build-almalinux-8:latest
  annotations:
    screwdriver.cd/restrictPR: fork
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash

jobs:
  test-system-tests:
    requires: [~pr, ~commit]
    environment:
      USER_SHELL_BIN: bash
      RUBYLIB: $SD_SOURCE_DIR/lib
    steps:
      - require-test-files: |
          export VESPA_FACTORY_NO_AUTORUNNER=1
          for FILE in $(find tests -name "*.rb"); do
            ruby  -I lib -I tests -I . -e "require '$FILE'"
          done
      - run-unit-tests: |
          set -e
          cd ${RUBYLIB}
          ruby test/testrunner.rb
          exit $?
