# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

require 'indexed_search_test'

class BigIndexClosure < IndexedSearchTest

  def setup
    set_owner("musum")
  end

  def test_big_index_closure
    deploy_app(SearchApp.new.sd(selfdir + "bigindexclosure.sd"))
    start
    feed_and_wait_for_docs("bigindexclosure", 2, :file => selfdir + "feed.xml")

    assert(search("query=a:testA1&ranking=unranked").hit.size == 1)
    assert_result("query=a:testA1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=b:testB1&ranking=unranked").hit.size == 1)
    assert_result("query=b:testB1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=c:testC1&ranking=unranked").hit.size == 1)
    assert_result("query=c:testC1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=d:testD1&ranking=unranked").hit.size == 1)
    assert_result("query=d:testD1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=e:testE1&ranking=unranked").hit.size == 1)
    assert_result("query=e:testE1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=f:testF1&ranking=unranked").hit.size == 1)
    assert_result("query=f:testF1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=g:testG1&ranking=unranked").hit.size == 1)
    assert_result("query=g:testG1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=h:testH1&ranking=unranked").hit.size == 1)
    assert_result("query=h:testH1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=i:testI1&ranking=unranked").hit.size == 1)
    assert_result("query=i:testI1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=j:testJ1&ranking=unranked").hit.size == 1)
    assert_result("query=j:testJ1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=k:testK1&ranking=unranked").hit.size == 1)
    assert_result("query=k:testK1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=l:testL1&ranking=unranked").hit.size == 1)
    assert_result("query=l:testL1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=m:testM1&ranking=unranked").hit.size == 1)
    assert_result("query=m:testM1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=n:testN1&ranking=unranked").hit.size == 1)
    assert_result("query=n:testN1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=o:testO1&ranking=unranked").hit.size == 1)
    assert_result("query=o:testO1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=p:testP1&ranking=unranked").hit.size == 1)
    assert_result("query=p:testP1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=q:testQ1&ranking=unranked").hit.size == 1)
    assert_result("query=q:testQ1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=r:testR1&ranking=unranked").hit.size == 1)
    assert_result("query=r:testR1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=s:testS1&ranking=unranked").hit.size == 1)
    assert_result("query=s:testS1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=t:testT1&ranking=unranked").hit.size == 1)
    assert_result("query=t:testT1&ranking=unranked", selfdir + "doc1.result.json")

    assert(search("query=a:testA2&ranking=unranked").hit.size == 1)
    assert_result("query=a:testA2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=b:testB2&ranking=unranked").hit.size == 1)
    assert_result("query=b:testB2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=c:testC2&ranking=unranked").hit.size == 1)
    assert_result("query=c:testC2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=d:testD2&ranking=unranked").hit.size == 1)
    assert_result("query=d:testD2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=e:testE2&ranking=unranked").hit.size == 1)
    assert_result("query=e:testE2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=f:testF2&ranking=unranked").hit.size == 1)
    assert_result("query=f:testF2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=g:testG2&ranking=unranked").hit.size == 1)
    assert_result("query=g:testG2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=h:testH2&ranking=unranked").hit.size == 1)
    assert_result("query=h:testH2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=i:testI2&ranking=unranked").hit.size == 1)
    assert_result("query=i:testI2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=j:testJ2&ranking=unranked").hit.size == 1)
    assert_result("query=j:testJ2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=k:testK2&ranking=unranked").hit.size == 1)
    assert_result("query=k:testK2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=l:testL2&ranking=unranked").hit.size == 1)
    assert_result("query=l:testL2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=m:testM2&ranking=unranked").hit.size == 1)
    assert_result("query=m:testM2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=n:testN2&ranking=unranked").hit.size == 1)
    assert_result("query=n:testN2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=o:testO2&ranking=unranked").hit.size == 1)
    assert_result("query=o:testO2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=p:testP2&ranking=unranked").hit.size == 1)
    assert_result("query=p:testP2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=q:testQ2&ranking=unranked").hit.size == 1)
    assert_result("query=q:testQ2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=r:testR2&ranking=unranked").hit.size == 1)
    assert_result("query=r:testR2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=s:testS2&ranking=unranked").hit.size == 1)
    assert_result("query=s:testS2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=t:testT2&ranking=unranked").hit.size == 1)
    assert_result("query=t:testT2&ranking=unranked", selfdir + "doc2.result.json")

    assert(search("query=testA1&ranking=unranked").hit.size == 1)
    assert_result("query=testA1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testB1&ranking=unranked").hit.size == 1)
    assert_result("query=testB1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testC1&ranking=unranked").hit.size == 1)
    assert_result("query=testC1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testD1&ranking=unranked").hit.size == 1)
    assert_result("query=testD1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testE1&ranking=unranked").hit.size == 1)
    assert_result("query=testE1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testF1&ranking=unranked").hit.size == 1)
    assert_result("query=testF1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testG1&ranking=unranked").hit.size == 1)
    assert_result("query=testG1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testH1&ranking=unranked").hit.size == 1)
    assert_result("query=testH1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testI1&ranking=unranked").hit.size == 1)
    assert_result("query=testI1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testJ1&ranking=unranked").hit.size == 1)
    assert_result("query=testJ1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testK1&ranking=unranked").hit.size == 1)
    assert_result("query=testK1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testL1&ranking=unranked").hit.size == 1)
    assert_result("query=testL1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testM1&ranking=unranked").hit.size == 1)
    assert_result("query=testM1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testN1&ranking=unranked").hit.size == 1)
    assert_result("query=testN1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testO1&ranking=unranked").hit.size == 1)
    assert_result("query=testO1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testP1&ranking=unranked").hit.size == 1)
    assert_result("query=testP1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testQ1&ranking=unranked").hit.size == 1)
    assert_result("query=testQ1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testR1&ranking=unranked").hit.size == 1)
    assert_result("query=testR1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testS1&ranking=unranked").hit.size == 1)
    assert_result("query=testS1&ranking=unranked", selfdir + "doc1.result.json")
    assert(search("query=testT1&ranking=unranked").hit.size == 1)
    assert_result("query=testT1&ranking=unranked", selfdir + "doc1.result.json")

    assert(search("query=testA2&ranking=unranked").hit.size == 1)
    assert_result("query=testA2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testB2&ranking=unranked").hit.size == 1)
    assert_result("query=testB2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testC2&ranking=unranked").hit.size == 1)
    assert_result("query=testC2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testD2&ranking=unranked").hit.size == 1)
    assert_result("query=testD2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testE2&ranking=unranked").hit.size == 1)
    assert_result("query=testE2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testF2&ranking=unranked").hit.size == 1)
    assert_result("query=testF2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testG2&ranking=unranked").hit.size == 1)
    assert_result("query=testG2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testH2&ranking=unranked").hit.size == 1)
    assert_result("query=testH2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testI2&ranking=unranked").hit.size == 1)
    assert_result("query=testI2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testJ2&ranking=unranked").hit.size == 1)
    assert_result("query=testJ2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testK2&ranking=unranked").hit.size == 1)
    assert_result("query=testK2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testL2&ranking=unranked").hit.size == 1)
    assert_result("query=testL2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testM2&ranking=unranked").hit.size == 1)
    assert_result("query=testM2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testN2&ranking=unranked").hit.size == 1)
    assert_result("query=testN2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testO2&ranking=unranked").hit.size == 1)
    assert_result("query=testO2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testP2&ranking=unranked").hit.size == 1)
    assert_result("query=testP2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testQ2&ranking=unranked").hit.size == 1)
    assert_result("query=testQ2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testR2&ranking=unranked").hit.size == 1)
    assert_result("query=testR2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testS2&ranking=unranked").hit.size == 1)
    assert_result("query=testS2&ranking=unranked", selfdir + "doc2.result.json")
    assert(search("query=testT2&ranking=unranked").hit.size == 1)
    assert_result("query=testT2&ranking=unranked", selfdir + "doc2.result.json")
  end

  def teardown
      stop
  end
end
