# Copyright Vespa.ai. All rights reserved.

ARG BASE_IMAGE=docker.io/almalinux:8
ARG VESPA_BASE_IMAGE=vespa

# Vespa install
FROM $BASE_IMAGE AS vespa

RUN dnf install -y dnf-plugins-core && \
    dnf install -y epel-release && \
    dnf config-manager --add-repo https://copr.fedorainfracloud.org/coprs/g/vespa/vespa/repo/epel-8/group_vespa-vespa-epel-8.repo && \
    dnf config-manager --enable powertools && \
    dnf config-manager --enable epel && \
    dnf -y upgrade && \
    dnf install -y vespa && \
    dnf clean --enablerepo=* all

RUN dnf install -y gcc-c++ python3-devel && \
    pip3 install --no-cache-dir --upgrade pip  && \
    dnf remove -y gcc-c++ python3-devel && \
    yum clean --enablerepo=* all

FROM $VESPA_BASE_IMAGE AS systemtest

ARG GCC_VERSION=15
ARG JAVA_VERSION=17
ARG RUBY_VERSION=3.1

ENV LANG=en_US.UTF-8
ENV RUBYLIB=/opt/vespa-systemtests/lib:/opt/vespa-systemtests/tests
ENV VESPA_CONFIGPROXY_JVMARGS="-XX:ThreadStackSize=1024k"
ENV VESPA_HOME=/opt/vespa
ENV VESPA_TLS_CONFIG_FILE=/opt/vespa/conf/vespa/tls/tls_config.json

USER root

RUN --mount=type=bind,target=/context-root,source=.,ro \
    sh /context-root/include/install-alma8.sh

# We want to have the system test files owned by root to detect any tests
# that might want to write into this location.
COPY /vespa-systemtests /opt/vespa-systemtests

# Currently both the root and vespa user need the cert/key because the
# test controller must run as root. This can be changed to only vespa user
# when/if the restriction is lifted.
RUN /opt/vespa-systemtests/docker/include/setup-tls.sh root

# When running the system tests as vespa we require an additional
# set of locations to be available and writable by the user. The
# statements below are required for system tests to run currently.
RUN chown vespa:vespa /opt/vespa && \
    cp -a /root/.vespa /opt/vespa && \
    chown -R vespa:vespa /opt/vespa/.vespa && \
    chown -R vespa:vespa /opt/vespa/.m2 && \
    chown -R vespa:vespa /opt/vespa/conf/vespa && \
    chown -R vespa:vespa /opt/vespa/conf/configserver-app && \
    chown -R vespa:vespa /opt/vespa/etc/vespa

COPY --chown=vespa:vespa /include/feature-flags.json /opt/vespa/var/vespa/flag.db

USER vespa

RUN --mount=type=bind,target=/context-root,source=./,ro \
    sh $VESPA_HOME/.m2/populate-m2-repo.sh vespa && \
    rm -f $VESPA_HOME/.m2/settings.xml $VESPA_HOME/.m2/populate-m2-repo.sh

ENTRYPOINT ["bash", "-lc", "source /opt/rh/gcc-toolset/enable && /opt/vespa-systemtests/lib/node_server.rb $NODE_SERVER_OPTS"]
