# Copyright Vespa.ai. All rights reserved.

require 'performance_test'
require 'app_generator/search_app'
require 'app_generator/container'
require 'performance/fbench'
require 'uri'

class MapSearchPerfTest < PerformanceTest

  def setup
    super
    set_owner("arnej")
  end

  def test_map_search
    set_description("Test performance of searching map attributes by value, range, key and sameElement(key, value)")
    # See create_docs.cpp for details on how the dataset is generated and which queries
    # that are available for exploring performance.
    add_bundle(selfdir + "MapSearchDocProc.java")
    deploy_app(create_app)
    @container = vespa.container.values.first
    compile_create_docs
    start

    # Must match the dataset generated by create_docs.cpp. Each entry is the mean of the
    # exponential distribution used for the entry count of the corresponding map field.
    @map_sizes = [5, 25, 125]
    @query_types = [:value, :range, :same_element, :combined]
    # Keys used by the :same_element queries. The selectivity of a key
    # varies per map field, since key "kK" is only present in documents whose map got
    # more than K entries.
    @query_keys = ["k0", "k5", "k20", "k100", "k150"]
    # Normal value distribution used for map values in create_docs.cpp (must match).
    @value_mean = 1000
    @value_stddev = 100
    @num_docs = 100000
    feed_docs
    validate_data
    run_query_and_profile
  end

  def create_app
    SearchApp.new.sd(selfdir + "test.sd").
       threads_per_search(1).
       container(Container.new("default").
                 search(Searching.new).
                 docproc(DocumentProcessing.new.
                         chain(Chain.new("default").
                               add(DocumentProcessor.new("com.yahoo.vespatest.MapSearchDocProc")))).
                 documentapi(ContainerDocumentApi.new))
  end

  def compile_create_docs
    tmp_bin_dir = @container.create_tmp_bin_dir
    @create_docs = "#{tmp_bin_dir}/create_docs"
    @container.execute("g++ -Wl,-rpath,#{Environment.instance.vespa_home}/lib64/ -g -O3 -o #{@create_docs} #{selfdir}/create_docs.cpp")
  end

  def feed_docs
    command = "#{@create_docs} -d #{@num_docs}"
    run_stream_feeder(command, [])
  end

  def run_query_and_profile
    for map_size in @map_sizes do
      for query_type in @query_types do
        for key in query_keys(query_type) do
          for qval in query_values(query_type) do
            expected = expected_hits(map_size, query_type, key, qval)
            label = get_label(map_size, query_type, key, qval)
            if expected < 1.0
              puts "skipping #{label}: expected hits #{expected.round(2)} < 1"
              next
            end
            puts "profiling #{label}: expected hits ~#{expected.round(1)}"
            query_and_profile(map_size, query_type, key, qval)
          end
        end
      end
    end
  end

  # The key(s) the query restricts to. :value matches across all entries (keyless); the
  # other query types sweep @query_keys.
  def query_keys(query_type)
    query_type == :value ? [nil] : @query_keys
  end

  # The value(s) the query matches against. :value and :same_element sweep several points
  # from the lower half of the value distribution up to its mean.
  def query_values(query_type)
    [500, 700, 900, 1000]
  end

  # Estimated number of matching documents (out of @num_docs) for a query, using the
  # distributions in create_docs.cpp. See the per-type derivations below.
  def expected_hits(map_size, query_type, key, qval)
    mean = map_size
    case query_type
    when :value
      # P(a doc has >= 1 entry with value == qval). Mean entry count is 1/(1 - e^(-1/mean)).
      mean_entries = 1.0 / (1.0 - Math.exp(-1.0 / mean))
      @num_docs * (1.0 - Math.exp(-mean_entries * p_value(qval)))
    when :range
      # Key "kK" present (a single entry) AND that entry's value in [qval-10, qval+10].
      p_range = ((qval-10)..(qval+10)).sum { |v| p_value(v) }
      @num_docs * p_key_present(key, mean) * p_range
    when :same_element, :combined
      # Key "kK" present (a single entry) AND that entry's value == qval. The
      # :combined type asks the same question via the "<name>_combined_attr" field.
      @num_docs * p_key_present(key, mean) * p_value(qval)
    end
  end

  # P(key "kK" is present in a map field): the entry count is (1 + int(r)) with
  # r ~ exponential(mean), so "kK" is present iff r >= K, with probability e^(-K/mean).
  def p_key_present(key, mean)
    Math.exp(-key[1..-1].to_i / mean)
  end

  # P(a normally distributed value rounds to integer v), approximated by the density.
  def p_value(v)
    Math.exp(-((v - @value_mean)**2) / (2.0 * @value_stddev**2)) /
      (@value_stddev * Math.sqrt(2 * Math::PI))
  end

  def get_yql(map_size, query_type, key, qval)
    field = "kv_#{map_size}"
    case query_type
    when :value
      # Match documents where any map entry has value 'qval'.
      "select * from sources * where #{field}.value = #{qval}"
    when :range
      # Match documents where the entry with key 'key' has its value within [qval-10, qval+10].
      "select * from sources * where #{field} contains sameElement(key contains \"#{key}\", range(value, #{qval-10}, #{qval+10}))"
    when :same_element
      # Match documents where the entry with key 'key' has value 'qval'.
      "select * from sources * where #{field} contains sameElement(key contains \"#{key}\", value = #{qval})"
    when :combined
      # Match the combined key/value attribute directly. The value is formatted as an
      # 8-digit unsigned hex number, matching MapSearchDocProc's "key#%08x" encoding.
      "select * from sources * where #{field}_combined_attr contains \"#{key}##{"%08x" % qval}\""
    else
      raise "Unknown query type: #{query_type}"
    end
  end

  def get_query(map_size, query_type, key, qval)
    "/search/?" + URI.encode_www_form("yql" => get_yql(map_size, query_type, key, qval),
                                      "hits" => "0")
  end

  def get_label(map_size, query_type, key, qval)
    key_part = key ? "_#{key}" : ""
    "query_m#{map_size}_#{query_type}#{key_part}_v#{qval}"
  end

  def query_file_name(map_size, query_type, key, qval)
    label = get_label(map_size, query_type, key, qval)
    dirs.tmpdir + "#{label}.txt"
  end

  def write_query_file(map_size, query_type, key, qval)
    file_name = query_file_name(map_size, query_type, key, qval)
    File.open(file_name, 'w') do |f|
      if query_type == :range
        # A range query already spans an interval, so emit it as a single query.
        f.puts(get_query(map_size, query_type, key, qval))
      else
        for v in (qval-10)..(qval+10) do
          f.puts(get_query(map_size, query_type, key, v))
        end
      end
    end
    file_name
  end

  # Sanity-checks the generated dataset against the distributions in create_docs.cpp.
  def validate_data
    for map_size in @map_sizes do
      field = "kv_#{map_size}"
      # Every map has at least one entry, so key "k0" is present in every document.
      assert_hitcount(key_query(field, "k0"), @num_docs)
      # Key "k20" is present only when the map got >= 21 entries. The entry count is
      # (1 + int(r)) with r ~ exponential(mean), so P(entries >= 21) = P(r >= 20) =
      # exp(-20 / mean), which differs per map field.
      expected = @num_docs * Math.exp(-20.0 / map_size)
      assert_hitcount_in_range(key_query(field, "k20"), expected)
    end
  end

  def key_query(field, key)
    "/search/?" + URI.encode_www_form(
      "yql" => "select * from sources * where #{field}.key contains \"#{key}\"",
      "hits" => "0")
  end

  # Asserts that the query hit count is within 5 standard deviations of 'expected',
  # treating the count as Binomial(@num_docs, expected / @num_docs).
  def assert_hitcount_in_range(query, expected)
    actual = search(query).hitcount
    p = expected / @num_docs
    sigma = Math.sqrt(@num_docs * p * (1.0 - p))
    lo = (expected - 5 * sigma).floor
    hi = (expected + 5 * sigma).ceil
    puts "#{query} -> #{actual} hits (expected ~#{expected.round}, allowed [#{lo}, #{hi}])"
    assert(actual >= lo && actual <= hi,
           "Hit count #{actual} for '#{query}' outside [#{lo}, #{hi}] (expected ~#{expected.round})")
  end

  def copy_to_container(source_file)
    dest_dir = dirs.tmpdir + "queries"
    @container.copy(source_file, dest_dir)
    dest_file = dest_dir + "/" + File.basename(source_file)
  end

  def query_and_profile(map_size, query_type, key, qval)
    local_query_file = write_query_file(map_size, query_type, key, qval)
    container_query_file = copy_to_container(local_query_file)
    label = get_label(map_size, query_type, key, qval)
    result_file = dirs.tmpdir + "fbench_result_#{label}.txt"
    fillers = [parameter_filler("label", label),
               parameter_filler("map_size", map_size),
               parameter_filler("query_type", query_type.to_s),
               parameter_filler("query_key", key || "any"),
               parameter_filler("query_value", qval)]
    profiler_start
    run_fbench2(@container,
                container_query_file,
                {:runtime => 5,
                 :clients => 1,
                 :append_str => "&timeout=10s&ranking.profile=unranked",
                 :result_file => result_file},
                fillers)
    profiler_report(label)
    @container.execute("head -12 #{result_file}")
  end

end
