# Copyright 2019 Oath Inc. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

require 'indexed_search_test'

class AccessLogTest < IndexedSearchTest

  def setup
    set_owner("bjorncs")
    set_description("Verify that search request are stored in default access log format")
    deploy_app(SearchApp.new.
               container(Container.new.
                   search(Searching.new).
                   docproc(DocumentProcessing.new).
                   component(AccessLog.new("vespa").
                       fileNamePattern("logs/vespa/access/QueryAccessLog.default"))).
               sd(SEARCH_DATA+"music.sd"))
    start
  end

  def test_accesslog
    feed_and_wait_for_docs("music", 777, :file => SEARCH_DATA+"music.777.xml")

    assert_hitcount("query=sddocname:music", 777)
    sleep 5 # wait for log to be written to disk
    log = vespa.container.values.first.get_query_access_log

    puts "LOG:'" + log + "'"

    monitor_line = Regexp.new('.* \/monitor\.html')
    correct_format = Regexp.new('(\S+) (\S+) (\S+) \[([^:]+):(\d+:\d+:\d+) ([^\]]+)\] "(\S+) (.*?) (\S+) (\S+) (\S+)')

    count = 0
    log.each_line { |line|
      if line =~ monitor_line
        # ignore lines generated by other processes
      elsif line =~ correct_format
        count = count + 1
      end
    }

    assert(count >= 1)

    puts log.inspect
  end

  def teardown
    stop
  end

end
